language: rust

matrix:
  include:
    - rust: stable
      script:
        - cargo +stable build --verbose
        - cargo +stable doc
    - rust: nightly
      before_script:
        - cargo +nightly install cargo-audit
      script:
        - cargo +nightly build --verbose
        - cargo +nightly audit
        - cargo +nightly test --verbose
        - cargo +nightly bench --verbose

